export default {
  login: 'olumide-eng',
  id: 68571111,
  node_id: 'MDQ6VXNlcjY4NTcxMTEx',
  avatar_url: 'https://avatars3.githubusercontent.com/u/68571111?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/olumide-eng',
  html_url: 'https://github.com/olumide-eng',
  followers_url: 'https://api.github.com/users/olumide-eng/followers',
  following_url:
    'https://api.github.com/users/olumide-eng/following{/other_user}',
  gists_url: 'https://api.github.com/users/olumide-eng/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/olumide-eng/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/olumide-eng/subscriptions',
  organizations_url: 'https://api.github.com/users/olumide-eng/orgs',
  repos_url: 'https://api.github.com/users/olumide-eng/repos',
  events_url: 'https://api.github.com/users/olumide-eng/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/olumide-eng/received_events',
  type: 'User',
  site_admin: false,
  name: 'olumide ilo',
  company: 'OluWebDev',
  blog: '',
  location: 'Lagos Nigeria',
  email: null,
  hireable: null,
  bio: 'Electrical/Electronics Engineer || Web Developer',
  twitter_username: 'ILO_olumide',
  public_repos: 3,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2020-07-20T23:26:42Z',
  updated_at: '2020-10-28T20:57:57Z',
}